import { Geist, Geist_Mono , Roboto} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistRoboto = Roboto({
  variable: "--font-geist-roboto",
  subsets: ["latin"],
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${geistRoboto.variable} font-roboto antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
