import { Geist, Geist_Mono , Roboto , Rubik, Anton} from "next/font/google";
import "./globals.css";

const geistRubic = Rubik({
  variable: "--font-geist-Rubic",
  subsets: ["arabic"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistAnton = Anton({
  variable: "--font-geist-Anton",
  weight: "400",
  subsets: ["latin"],
});
const geistRoboto = Roboto({
  variable: "--font-geist-roboto",
  subsets: ["latin"],
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning="true"
        className={` ${geistRoboto.variable} ${geistRubic.variable} ${geistAnton.variable} font-roboto antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
